#ifndef LIBYCVID_INCLUDE_TYPES_TEXTURE_VISIBILITY_H
#define LIBYCVID_INCLUDE_TYPES_TEXTURE_VISIBILITY_H

typedef enum yc_vid_texture_visibility {
    YC_VID_TEXTURE_VISIBILITY_OFF,
    YC_VID_TEXTURE_VISIBILITY_ON
} yc_vid_texture_visibility_t;

#endif //LIBYCVID_INCLUDE_TYPES_TEXTURE_VISIBILITY_H
