#ifndef LIBYCVID_INCLUDE_TYPES_TEXTURE_ORDER_H
#define LIBYCVID_INCLUDE_TYPES_TEXTURE_ORDER_H

typedef enum yc_vid_texture_order {
    YC_VID_TEXTURE_ORDER_FLOOR = 0,
    YC_VID_TEXTURE_ORDER_FLAT = 1,
    YC_VID_TEXTURE_ORDER_WALL = 2,
    YC_VID_TEXTURE_ORDER_SCENERY = 2,
    YC_VID_TEXTURE_ORDER_MISC = 2,
    YC_VID_TEXTURE_ORDER_ITEM = 2,
    YC_VID_TEXTURE_ORDER_CRITTER = 2,
    YC_VID_TEXTURE_ORDER_ROOF = INT8_MAX,
} yc_vid_texture_order_t;

#endif //LIBYCVID_INCLUDE_TYPES_TEXTURE_ORDER_H
