#ifndef LIBYCVID_INCLUDE_TYPES_TEXTURE_ORDER_H
#define LIBYCVID_INCLUDE_TYPES_TEXTURE_ORDER_H

typedef enum yc_vid_texture_order {
    YC_VID_TEXTURE_ORDER_FLOOR,
    YC_VID_TEXTURE_ORDER_FLAT,
    YC_VID_TEXTURE_ORDER_WALL,
    YC_VID_TEXTURE_ORDER_SCENERY,
    YC_VID_TEXTURE_ORDER_MISC,
    YC_VID_TEXTURE_ORDER_ITEM,
    YC_VID_TEXTURE_ORDER_CRITTER,
    YC_VID_TEXTURE_ORDER_ROOF,
} yc_vid_texture_order_t;

#endif //LIBYCVID_INCLUDE_TYPES_TEXTURE_ORDER_H
